### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by CMUgarte**
Straightforward update. no surprises.

### CODE REVIEW

**Review by FredericBlum — APPROVED** [review]
Please consult with @LinguList regarding this repository possibly being superseeded by baf2

**Comment by FredericBlum** [comment]
Please also check if #4 has been included

**Review by chrzyki — APPROVED** [review]

**Comment by CMUgarte** [comment]
@FredericBlum I forgot to close the issue. Thanks for the reminder :)

**Comment by CMUgarte** [comment]
> Please consult with @LinguList regarding this repository possibly being superseeded by baf2

@LinguList, on this note, can this repo be superseded by [baf2](https://github.com/lexibank/baf2) (since it has more concepts)?

**Comment by LinguList** [comment]
For Lexibank yes. There's even a new heathdogon, which is even larger, we should check if we can include that one as well. If we add two with identical data to the workflow, it should not hurt, as we later select one language for the forms anyway.

**Review by LinguList — APPROVED** [review]

**Review by FredericBlum — APPROVED** [review]

**Pull request merged**
